### ISSUE TITLE
update paketo-buildpacks / node-run-script to use libnodejs

### ISSUE THREAD

**Issue by mhdawson** [paketo-buildpacks/libnodejs#17]
## Describe the Enhancement

Update [node-run-script](https://github.com/paketo-buildpacks/node-run-script) to leverage libnodejs and the common definitions

## Motivation

Improve centralization of concerns.

**Comment by c0d1ngm0nk3y** [comment]
@mhdawson Any specific reason why this is not an issue on `node-run-script`?

**Comment by mhdawson** [comment]
@c0d1ngm0nk3y that might make more sense, I had opened it here as a reminder to look at it at some point.

**Comment by mhdawson** [comment]
@c0d1ngm0nk3y thanks for creating a PR to cover it :)

**Comment by c0d1ngm0nk3y** [comment]
> @c0d1ngm0nk3y that might make more sense, I had opened it here as a reminder to look at it at some point.

I was such curious. Maybe an issue on `libnodejs` for all buildpacks that could benefit from it would make sense. Or was `node-run-script` the last one?
